handlers:
    entities:
        blacklist: 
            - WANDERING_TRADER
            - LLAMA
            - PHANTOM
    storms:
        stop-delay-in-seconds: 3
        stopped-message: "&9Storm Stopped!"