handlers:
    entities:
        active: true
        blacklist: 
            - Wandering Trader
            - Llama
            - Phantom
            - Slime
    storms:
        active: true
        global-message: ""