handlers:
    entities:
        active: true
        blacklist: 
            - Wandering Trader
            - Llama
            - Phantom
    storms:
        active: true
        global-message: "&9Storm Stopped!"